<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BS-784" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="14 Feb 2022 11:07:30 GMT" time="0.064" errors="0">
  <testcase name="test3" time="0.018" classname="testng.TestNG_Retry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.TestNG_Retry.test3(TestNG_Retry.java:23)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.003" classname="testng.TestNG_Retry"/>
  <testcase name="test1" time="0.0" classname="testng.TestNG_Retry">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
